name: check
on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: set up job
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            with:
            node_version: 16
            - run: npm ci
            - name: run eslint
            - run: npx eslint ./src/*

    test:
        runs-on: ubuntu-latest
        steps:
            - name: set up job
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            with:
             node_version: 16
            -  run: npm ci
            - name: run unit tests
            - run: npm test --passWithNoTests