name: check
on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: set up job
              uses: actions/checkout@v2

            - name: set up node
              uses: actions/setup-node@v2
              with:
                node_version: 16

            - name: install dependencies
              run: npm ci

            - name: run eslint
              run: npx eslint ./src/*
